spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  datasource:
      url: jdbc:mysql://localhost:3306/sanji-boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  thymeleaf:
    cache: false
# Check that the templates location exists.
    check-template-location: true
# Content-Type value.
    content-type: text/html
# Enable MVC Thymeleaf view resolution.
    enabled: true
# Template encoding.
    encoding: UTF-8
# Comma-separated list of view names that should be excluded from resolution.
    mode: HTML5
# Prefix that gets prepended to view names when building a URL.
    prefix: classpath:/templates/
# Suffix that gets appended to view names when building a URL.
    suffix: .html
